name: flutter_login_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2  
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.1.0
  get:
  flutter_login: ^5.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth:
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.3+1
  intl: ^0.19.0
  firebase_database: ^11.1.3
  chat_gpt_sdk: ^3.1.0
  http: ^1.2.2
  cached_network_image: ^3.2.3
  url_launcher: ^6.0.20
  shared_preferences: ^2.3.2
  firebase_messaging:
  fl_chart: ^0.69.0
  csv:
  syncfusion_flutter_gauges: ^27.1.48
  health: ^11.0.0
  pedometer: ^4.0.2
  flutter_activity_recognition: ^4.0.0
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.3
  sensors_plus: ^6.0.1
  animated_text_kit: ^4.2.2
  convex_bottom_bar: ^3.2.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  workmanager: ^0.5.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_blue: ^0.8.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/AppLogo.png
    - assets/images/default_avatar.png
    - assets/images/doctor.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/app_preview.png
    - assets/images/AboutUs_1.png
    - assets/images/pill_icon.png
    - assets/images/whodrugs_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppLogo.png" # Đường dẫn đến biểu tượng của bạn
  adaptive_icon_background: "#FFFFFF" # Màu nền cho icon adaptive trên Android
  adaptive_icon_foreground: "assets/images/AppLogo.png" # Ảnh nền cho Android adaptive icon
